title: 村口小站
email: phmfk@hotmail.com
description: >
    我的技术博客，记录点滴感悟。
baseurl: ""
url: "https://gisphm.github.io" # the base hostname & protocol for your site
twitter_username: gisphm
github_username:  gisphm
weibo_username: phm8341

paginate: 5

markdown: redcarpet
highlighter: pygments
redcarpet:
    extensions:
        - smart

gems:
    - jemoji
    - jekyll-sitemap
